# Generated by Django 2.2.5 on 2020-01-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='keaktifan',
            field=models.BooleanField(default=True),
        ),
    ]
