# Generated by Django 2.1.7 on 2019-07-02 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kepalakeluarga',
            name='nama_kk',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Nama tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:",<>/?\\d]')]),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='nama',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Nama tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:",<>/?\\d]')]),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='tanggal_lahir',
            field=models.DateField(error_messages={'invalid': 'Format tanggal: dd/mm/yyyy model'}),
        ),
    ]
