# Generated by Django 2.1.7 on 2019-05-24 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='no_hp',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Nomor Handphone harus mengikuti format:                     '+628...' or '08...' maksimal 15 digit.", regex='^(\\+62|0)\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
