# Generated by Django 2.1.7 on 2019-06-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='watu_daftar',
            new_name='waktu_daftar',
        ),
    ]
