# Generated by Django 2.1.7 on 2019-06-28 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0002_auto_20190627_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=9),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='telp',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Format nomor handphone: '+628...' atau '08...',         maksimal 15 digit.", regex='^(\\+62|0)\\d{9,15}$')]),
        ),
    ]
