# Generated by Django 2.1.7 on 2019-07-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0002_auto_20190702_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
