# Generated by Django 2.2.1 on 2019-07-05 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0002_delete_hari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tempat', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Alamat tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:"<>/?]')])),
                ('alamat_tempat', models.TextField(validators=[django.core.validators.RegexValidator(inverse_match=True, message='Alamat tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:"<>/?]')])),
            ],
        ),
    ]
