# Generated by Django 2.1.7 on 2019-06-28 01:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0003_auto_20190628_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kepalakeluarga',
            name='nama',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Nama tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:",<>/?\\d]')]),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='pendaftaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antri.Pendaftaran', validators=[django.core.validators.RegexValidator(inverse_match=True, message='Nama tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:",<>/?\\d]')]),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='nama',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Nama tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:",<>/?\\d]')]),
        ),
    ]
