# Generated by Django 2.2.1 on 2019-07-06 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0003_tempat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.CharField(choices=[('PG', 'Pagi'), ('SG', 'Siang'), ('SR', 'Sore')], max_length=2)),
                ('waktu_buka', models.TimeField()),
                ('waktu_tutup', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=9),
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antri.Hari')),
                ('pasien_set', models.ManyToManyField(to='antri.Pasien')),
                ('tempat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antri.Tempat')),
            ],
        ),
    ]
