# Generated by Django 2.1.7 on 2019-06-28 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antri', '0004_auto_20190628_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kepalakeluarga',
            name='alamat',
            field=models.TextField(validators=[django.core.validators.RegexValidator(inverse_match=True, message='Alamat tidak boleh mengandung simbol yang aneh.', regex='[`~!@#$%^&*()_+=\\[\\]{}\\\\|;:"<>/?\\d]')]),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='telp',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Format nomor telepon: '+628...' atau '08...',         maksimal 15 digit.", regex='^(\\+62|0)\\d{9,15}$')]),
        ),
    ]
