# Generated by Django 2.1.7 on 2019-05-23 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0002_auto_20190523_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                     '+628...' or '08...'. Up to 15 digits allowed.", regex='^(\\+62|0)\\d{9,15}$')]),
        ),
    ]
